# ABI regression harness for the C header generator.
#
# The bar for the ClangCompiler migration is NOT byte-identical output — the design allows the
# generated code to improve (GENERATORS-REWORK.md §5.7). The bar is that nothing which
# generates and loads today stops doing so, and that every emitted type keeps the same memory
# layout.
#
# So this records, per fixture: whether the build completes, whether the generated file loads,
# and for every emitted concrete type its `sizeof` and field offsets. That triple is the
# contract. Run with CLANG_JL_WRITE_BASELINE=1 to (re)record; otherwise it compares.
#
#   julia --project -e 'using TestEnv; TestEnv.activate();
#                       ENV["CLANG_JL_WRITE_BASELINE"]="1"; include("test/abi_baseline.jl")'

using Test
using Clang
using Clang.Generators
using TOML

const HERE = @__DIR__
const BASELINE = joinpath(HERE, "abi_baseline.toml")
const WRITE = get(ENV, "CLANG_JL_WRITE_BASELINE", "") == "1"

# Objective-C is out of scope for the ClangCompiler backend until ClangCompiler#49.
const SKIP = Set(["objectiveC.h"])

"Fixtures that need `test/sys` on the include path."
const NEEDS_SYS = Set(["nested-struct.h", "nested-declaration.h", "struct-in-union.h", "test.h"])

fixtures() = sort!([f for f in readdir(joinpath(HERE, "include")) if endswith(f, ".h") && f ∉ SKIP])

"""
    probe(header) -> Dict

Generate `header`, load the result, and measure every concrete type it defined. Any failure is
recorded rather than thrown — a fixture that errors today is part of the baseline too, and
turning that error into a *different* error is itself a regression worth seeing.
"""
function probe(name::AbstractString)
    rec = Dict{String,Any}("build" => "ok", "load" => "ok", "types" => Dict{String,Any}())
    dir = mktempdir()
    out = joinpath(dir, "Lib.jl")
    args = get_default_args()
    name in NEEDS_SYS && push!(args, "-isystem" * joinpath(HERE, "sys"))
    options = Dict("general" => Dict{String,Any}("library_name" => "libregression",
                                                 "output_file_path" => out))
    try
        ctx = create_context([joinpath(HERE, "include", name)], args, options)
        build!(ctx)
    catch err
        rec["build"] = sprint(showerror, err) |> first_line
        rec["load"] = "n/a"
        return rec
    end

    m = Module(Symbol("ABI_", replace(name, r"[^A-Za-z0-9]" => "_")))
    Core.eval(m, :(using CEnum: CEnum, @cenum))
    Core.eval(m, :(const libregression = "libregression"))
    try
        Base.include(m, out)
    catch err
        rec["load"] = sprint(showerror, err) |> first_line
        return rec
    end

    # `Base.include` defines these bindings in a NEWER world age than this function was
    # compiled in, so a direct `names`/`isdefined` here sees nothing. Measuring through
    # `invokelatest` is the documented way across that boundary — and getting it wrong is
    # silent: the loop simply finds zero types and the baseline looks empty but valid.
    merge!(rec["types"], Base.invokelatest(measure, m))
    return rec
end

"Every concrete struct type `m` defines, with its size and field offsets."
function measure(m::Module)
    out = Dict{String,Any}()
    for nm in names(m; all=true)
        startswith(string(nm), "#") && continue
        isdefined(m, nm) || continue
        v = try getfield(m, nm) catch; continue end
        v isa DataType || continue
        (isconcretetype(v) && isstructtype(v)) || continue
        parentmodule(v) === m || continue
        try
            entry = Dict{String,Any}("sizeof" => Int(sizeof(v)))
            fc = fieldcount(v)
            if fc > 0
                entry["offsets"] = [Int(fieldoffset(v, i)) for i = 1:fc]
                entry["fields"] = [string(f) for f in fieldnames(v)]
            end
            out[string(nm)] = entry
        catch
            # an opaque marker type has no layout; not an ABI fact
        end
    end
    return out
end

first_line(s) = first(split(s, "\n"))

function capture()
    all = Dict{String,Any}()
    for f in fixtures()
        all[f] = probe(f)
    end
    return all
end

if WRITE
    data = capture()
    open(BASELINE, "w") do io
        println(io, "# Generated by test/abi_baseline.jl — do not hand-edit.")
        println(io, "# Re-record with CLANG_JL_WRITE_BASELINE=1 only when a change to the")
        println(io, "# generated output is intended and reviewed.")
        TOML.print(io, data; sorted=true)
    end
    n = sum(length(v["types"]) for v in values(data))
    @info "wrote baseline" fixtures=length(data) types=n path=BASELINE
else
    @testset "ABI baseline (C header generator)" begin
        if !isfile(BASELINE)
            @info "no baseline recorded; run with CLANG_JL_WRITE_BASELINE=1"
            @test_skip false
        else
            expected = TOML.parsefile(BASELINE)
            actual = capture()
            @test sort(collect(keys(actual))) == sort(collect(keys(expected)))
            for f in sort(collect(keys(expected)))
                haskey(actual, f) || continue
                e, a = expected[f], actual[f]
                @testset "$f" begin
                    @test a["build"] == e["build"]
                    @test a["load"] == e["load"]
                    # every type in the baseline must still exist with the same layout
                    for (ty, ev) in e["types"]
                        @test haskey(a["types"], ty)
                        haskey(a["types"], ty) || continue
                        @test a["types"][ty]["sizeof"] == ev["sizeof"]
                        @test get(a["types"][ty], "offsets", nothing) == get(ev, "offsets", nothing)
                    end
                end
            end
        end
    end
end
